name: Java CI with Maven # 워크플로우 이름

on:
  push:
    branches: [ "main" ] # main 브랜치에 코드를 푸시할 때 워크플로우 실행
  pull_request:
    branches: [ "main" ] # PR 시에도 워크플로우 실행 (배포는 PR에서 보통 제외)

jobs:
  build: # 빌드 잡: 프로젝트를 빌드하고 JAR 파일을 아티팩트로 저장
    runs-on: ubuntu-latest # GitHub Actions 런너 환경
    permissions:
      contents: write # Dependabot Dependency Graph 제출에 필요

    steps:
    - uses: actions/checkout@v4 # 저장소 코드 체크아웃
    - name: Set up JDK 17
      uses: actions/setup-java@v4 # JDK 17 설정
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven # Maven 캐시 활성화

    - name: Build with Maven
      run: mvn -B package --file pom.xml # Maven 빌드 실행 (JAR 파일 생성)

    # 빌드된 JAR 파일을 아티팩트로 업로드합니다.
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: budgets-backend-jar # 아티팩트 이름 (deploy 잡에서 이 이름으로 다운로드합니다)
        path: target/*.jar # 일반적으로 `target/*.jar`는 빌드된 JAR 파일을 자동으로 찾아 업로드합니다.

    - name: Update dependency graph # 종속성 그래프 제출 (기존 기능 유지)
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  # --- 새로운 잡: JAR 파일만 서버로 전송 ---
  transfer_jar:
    needs: build # build 잡이 성공하면 실행
    runs-on: ubuntu-latest
    environment: production # Secret 관리를 위함
    steps:
      - name: Download JAR artifact # 'build' 잡에서 업로드한 JAR 파일을 다운로드합니다.
        uses: actions/download-artifact@v4
        with:
          name: budgets-backend-jar
          path: ./downloaded-jar

      - name: Verify JAR on Runner before SCP # SCP 전 런너에 JAR 파일이 있는지 확인 (디버깅 유지)
        run: |
          echo "현재 런너 워킹 디렉토리: $(pwd)"
          echo "다운로드 디렉토리 내용 (./downloaded-jar/):"
          ls -l ./downloaded-jar/
          echo "예상 JAR 파일 경로: ./downloaded-jar/budgets_backend-00.1-SNAPSHOT.jar"
          echo "예상 JAR 파일 존재 여부 확인:"
          ls -l "./downloaded-jar/budgets_backend-00.1-SNAPSHOT.jar" || echo "파일을 찾을 수 없습니다!"
          echo "find 명령어로 전체 검색 (혹시 다른 곳에 있는지):"
          find . -name "*.jar"

      # --- 직접 SCP 전송 시작 ---
      - name: Setup SSH for direct SCP # SSH 키 설정
        uses: webfactory/ssh-agent@v0.8.0 # ssh-agent 설정 액션
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # GitHub Secret에서 개인 키 가져옴

      - name: Add Server to known_hosts # 서버 호스트 키 등록
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Transfer JAR to Server via direct SCP # 직접 SCP 명령으로 JAR 파일 전송 (이 잡의 핵심 스텝)
        run: |
          # SSH 접속 포트를 명시적으로 지정
          SCP_COMMAND="scp -P ${{ secrets.SSH_PORT }} ./downloaded-jar/budgets_backend-00.1-SNAPSHOT.jar ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.APP_PATH }}/budgets_backend-00.1-SNAPSHOT.jar"
          echo "실행할 SCP 명령어: ${SCP_COMMAND}"
          ${SCP_COMMAND}
          echo "SCP 전송 완료. 서버에 파일이 있는지 확인하십시오."
      # --- 직접 SCP 전송 끝 ---

  # --- 새로운 잡: 원격 스크립트 실행 ---
  run_remote_script:
    needs: transfer_jar # JAR 파일 전송 잡이 성공하면 실행
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Run Remote Deployment Script # 서버에서 배포 스크립트 실행
        uses: appleboy/ssh-action@master # SSH 접속 및 명령 실행을 위한 GitHub Action
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          
          script: |
            echo "--- 배포 시작 (원격 스크립트) ---"

            # 1. 서버에 배포될 디렉토리가 없으면 생성합니다.
            mkdir -p ${{ secrets.APP_PATH }}
            echo "배포 디렉토리 확인/생성 완료: ${{ secrets.APP_PATH }}"

            # --- JAR 파일 존재 여부 디버깅 시작 (서버) ---
            # SCP 성공 시 이 ls 명령에서 파일이 보여야 합니다.
            echo "서버 배포 경로 (${{ secrets.APP_PATH }}) 내용:"
            ls -l ${{ secrets.APP_PATH }}/
            echo "서버에 복사된 JAR 파일 (${{ secrets.APP_PATH }}/budgets_backend-00.1-SNAPSHOT.jar) 확인:"
            ls -l ${{ secrets.APP_PATH }}/budgets_backend-00.1-SNAPSHOT.jar || echo "서버에서 JAR 파일을 찾을 수 없습니다!"
            # --- JAR 파일 존재 여부 디버깅 끝 ---

            # 2. 애플리케이션 재시작
            echo "애플리케이션 서비스를 재시작합니다..."
            sudo systemctl daemon-reload
            sudo systemctl restart budgets-backend.service || { echo "ERROR: 서비스 재시작 실패. 서버에서 systemctl status budgets-backend.service 명령으로 상태 확인."; exit 1; }
            echo "서비스 재시작 명령 전송 완료."
            
            # 3. (선택 사항) 서비스 시작 후 잠시 대기 및 상태 확인
            sleep 10
            echo "서비스 상태를 확인합니다..."
            sudo systemctl status budgets-backend.service | head -n 10
            
            echo "--- 배포 완료 (원격 스크립트) ---"
